/*ALTER COMPANIES TABLE */
ALTER TABLE companies
ADD street_1 VARCHAR(255);

ALTER TABLE companies
ADD street_2 VARCHAR(255);

ALTER TABLE companies
ADD city VARCHAR(255);

ALTER TABLE companies
ADD state VARCHAR(255);

ALTER TABLE companies
ADD zip_code VARCHAR(255);


/*ALTER EDUCATIONS TABLE*/
ALTER TABLE educations
ADD street_1 VARCHAR(255);

ALTER TABLE educations
ADD street_2 VARCHAR(255);

ALTER TABLE educations
ADD city VARCHAR(255);

ALTER TABLE educations
ADD state VARCHAR(255);

ALTER TABLE educations
ADD zip_code VARCHAR(255);