ALTER TABLE projects
ALTER COLUMN title VARCHAR(255) DEFAULT NULL;

ALTER TABLE projects
ALTER COLUMN description VARCHAR(255) DEFAULT NULL;

ALTER TABLE addresses
ALTER COLUMN street_1 VARCHAR(255) DEFAULT NULL;

ALTER TABLE addresses
ALTER COLUMN city VARCHAR(255) DEFAULT NULL;

ALTER TABLE addresses
ALTER COLUMN state VARCHAR(255) DEFAULT NULL;

ALTER TABLE addresses
ALTER COLUMN zip_code VARCHAR(255) DEFAULT NULL;

ALTER TABLE positions
ALTER COLUMN name VARCHAR(255) DEFAULT NULL;

ALTER TABLE positions
ALTER COLUMN company_id BIGINT(20) DEFAULT NULL;

ALTER TABLE contacts
ALTER COLUMN position VARCHAR(255) DEFAULT NULL;

ALTER TABLE contacts
ALTER COLUMN first_name VARCHAR(255) DEFAULT NULL;

ALTER TABLE contacts
ALTER COLUMN email VARCHAR(255) DEFAULT NULL;

ALTER TABLE contacts
ALTER COLUMN phone_number VARCHAR(255) DEFAULT NULL;

ALTER TABLE educations
ALTER COLUMN school_name VARCHAR(255) DEFAULT NULL;

ALTER TABLE educations
ALTER COLUMN field_of_study VARCHAR(255) DEFAULT NULL;

ALTER TABLE companies
ALTER COLUMN name VARCHAR(255) DEFAULT NULL;

ALTER TABLE certifications
ALTER COLUMN name VARCHAR(255) DEFAULT NULL;